# ######################################################################################## 
# Configuration: TheWired
# For: Garuda Hyperland
# Date Last Modified: 06/20/2024
# Date Created: 06/20/2024
# ######################################################################################## 




# ######################################################################################## 

# WORKSPACES!!
# Name the workspace, and set the monitor it should apear on, here I have workspaces 4 
# and 5 Always apearing on my second vertical monitor.
# I have also set up a workspace for my tablet so I can ensure that Any Drawing application 
# appears there by defualt. 

# ######################################################################################## 

workspace = 1, name main , monitor:DP-1
workspace = 2, name:browsers, monitor:DP-2
workspace = 3, name:tablet, monitor:HDMI-A-1
workspace = 4, name:social, monitor:DP-2
workspace = 5, name:music, monitor:DP-2
workspace = 6, name:games, monitor:DP-1


# ######################################################################################## 

# Window RULES!!
# This is where you set up your rules for your windows. 
# Here i have my Discord and Element showing up on my second monitor by default in
# workspace 4 that I named "Social". I have also set up tidla to open on workspace 5
# that i named "music"

# ######################################################################################## 



windowrule{
    name = Discord
    match:class = discord
    workspace = 4
}

windowrule{
    name = Element
    match:class = Element
    workspace = 4
}

windowrule{
    name = Steam
    match:class = steam
    workspace = 5
}

windowrule{
    name = games
    match:class = gamescope
    workspace = 6
}

windowrule{
    name = steam_apps
    match:class = steam_app_default
    workspace = 6
}





# windowrulev2 = workspace:social, class:^(discord), title:^(Discord)
# windowrulev2 = workspace:social, class:^(Element), title:^(Element)s
# windowrulev2 = workspace:music, class:^(tidal-hifi), title:^(tidal-hifi)
# windowrulev2 = workspace:games, class:^(FFXIVLauncher), title:^(FFXIVLauncher)
# windowrulev2 = workspace:games, class:^(ffxiv_dx11), title:^(ffxiv_dx11)


# ######################################################################################## 

# DEFUALT Rules!!
# These are the rules that garuda has by default. 

# ######################################################################################## 


# Basic winrules float assigns window to float.

# windowrulev2 = float, class:^(kitty)$
# windowrulev2 = float, class:^(garuda-assistant)$
# windowrulev2= float, class:^(garuda-boot-options)$
# windowrulev2 = float, class:^(garuda-boot-repair)$
# windowrulev2 = float, class:^(garuda-gamer)$
# windowrulev2 = float, class:^(garuda-network-assistant)$
# windowrulev2 = float, class:^(garuda-settings-manager)$
# windowrulev2 = float, class:^(garuda-welcome)$


# Opacity settings
# windowrulev2 = opacity 0.85 override 0.85 override, class:^(thunar)$
# windowrulev2 = opacity 0.85 override 0.85 override, class:^(gedit)$
# windowrulev2 = opacity 0.85 override 0.85 override, class:^(catfish)$

# Focus Settings
# windowrulev2 = stayfocused, class:^(wofi)$


