# ######################################################################################## 
# Configuration: TheWired
# For: Garuda Hyperland
# Date Last Modified: 06/20/2024
# Date Created: 06/20/2024
# ######################################################################################## 




# ######################################################################################## 

# WORKSPACES!!
# Name the workspace, and set the monitor it should apear on, here I have workspaces 4 
# and 5 Always apearing on my second vertical monitor.
# I have also set up a workspace for my tablet so I can ensure that Any Drawing application 
# appears there by defualt. 

# ######################################################################################## 

workspace = 1, name:browsers, monitor:eDP-1
workspace = 2, name:android, monitor:DP-1
workspace = 3, name:research, monitor:eDP-1
workspace = 4, name:teams, monitor:eDP-1


# ######################################################################################## 

# Window RULES!!
# This is where you set up your rules for your windows. 
# Here i have my Discord and Element showing up on my second monitor by default in
# workspace 4 that I named "Social". I have also set up tidla to open on workspace 5
# that i named "music"

# ######################################################################################## 

windowrule{
    name = Teams
    match:class = teams-for-linux
    workspace = 4
}

windowrule{
    name = teams
    match:class = jetbrains-studio
    workspace = 2
}


# windowrule = workspace social, class:discord
# windowrule = workspace social, class:ELement

#windowrulev2 = workspace social, class:^(discord), title:^(Discord)
#windowrulev2 = workspace social, class:^(Element), title:^(Element)
#windowrulev2 = workspace music, class:^(tidal-hifi), title:^(tidal-hifi)
#windowrulev2 = workspace games, class:^(FFXIVLauncher), title:^(FFXIVLauncher)
#windowrulev2 = workspace games, class:^(ffxiv_dx11), title:^(ffxiv_dx11)


# ######################################################################################## 

# DEFUALT Rules!!
# These are the rules that garuda has by default. 

# ######################################################################################## 


# Basic winrules float assigns window to float.

# windowrule = float, class:^(kitty)$
# windowrule = float, class:^(garuda-assistant)$
# windowrule = float, class:^(garuda-boot-options)$
# windowrule = float, class:^(garuda-boot-repair)$
# windowrule = float, class:^(garuda-gamer)$
# windowrule = float, class:^(garuda-network-assistant)$
# windowrule = float, class:^(garuda-settings-manager)$
# windowrule = float, class:^(garuda-welcome)$


# Opacity settings
# windowrule = opacity 0.85 override 0.85 override,class:^(thunar)$
# windowrule = opacity 0.85 override 0.85 override,class:^(gedit)$
# windowrule = opacity 0.85 override 0.85 override,class:^(catfish)$

# Focus Settings
# windowrule = stayfocused, class:^(wofi)$


